# Reusable CI Pipeline Workflow
# Location: .github/workflows/reusable-ci.yml (in org/.github repository)
# Usage: Called from individual repository workflows

name: Reusable CI Pipeline

on:
  workflow_call:
    inputs:
      language:
        description: 'Programming language (node, python, java, go)'
        required: true
        type: string
      language-version:
        description: 'Language version (e.g., 18, 3.11, 17)'
        required: false
        type: string
        default: 'latest'
      build-command:
        description: 'Build command to execute'
        required: false
        type: string
        default: ''
      test-command:
        description: 'Test command to execute'
        required: true
        type: string
      lint-command:
        description: 'Lint command to execute'
        required: false
        type: string
        default: ''
      enable-docker:
        description: 'Build and push Docker image'
        required: false
        type: boolean
        default: false
      docker-registry:
        description: 'Docker registry (ghcr.io, ecr, acr)'
        required: false
        type: string
        default: 'ghcr.io'
      enable-security-scan:
        description: 'Run security scanning'
        required: false
        type: boolean
        default: true
      deployment-environment:
        description: 'Environment to deploy to (dev, staging, production)'
        required: false
        type: string
        default: ''
    secrets:
      aws-role-arn:
        description: 'AWS IAM role ARN for OIDC authentication'
        required: false
      azure-client-id:
        description: 'Azure client ID for OIDC authentication'
        required: false
      registry-username:
        description: 'Container registry username'
        required: false
      registry-password:
        description: 'Container registry password'
        required: false
      slack-webhook:
        description: 'Slack webhook for notifications'
        required: false
    outputs:
      artifact-url:
        description: 'URL of the published artifact'
        value: ${{ jobs.build.outputs.artifact-url }}
      image-digest:
        description: 'Docker image digest (if built)'
        value: ${{ jobs.docker.outputs.image-digest }}
      coverage-percentage:
        description: 'Test coverage percentage'
        value: ${{ jobs.test.outputs.coverage }}

# Minimal permissions by default
permissions:
  contents: read
  pull-requests: write
  id-token: write
  packages: write

jobs:
  # Job 1: Code Quality & Linting
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    if: inputs.lint-command != ''
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup language environment
        uses: ./.github/actions/setup-environment
        with:
          language: ${{ inputs.language }}
          version: ${{ inputs.language-version }}
          cache-dependency-path: |
            **/package-lock.json
            **/yarn.lock
            **/poetry.lock
            **/requirements.txt
            **/pom.xml
            **/build.gradle

      - name: Run linter
        run: ${{ inputs.lint-command }}

      - name: Upload lint results
        if: always()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: lint-results
          path: |
            **/lint-results.json
            **/eslint-report.json
            **/pylint-report.txt
          retention-days: 7

  # Job 2: Build
  build:
    name: Build Application
    runs-on: ubuntu-latest
    if: inputs.build-command != ''
    timeout-minutes: 20
    outputs:
      artifact-url: ${{ steps.upload.outputs.artifact-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Setup language environment
        uses: ./.github/actions/setup-environment
        with:
          language: ${{ inputs.language }}
          version: ${{ inputs.language-version }}

      - name: Restore build cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: |
            ~/.npm
            ~/.cache/pip
            ~/.m2/repository
            ~/.gradle/caches
            **/node_modules
            **/target
            **/build
          key: build-${{ runner.os }}-${{ inputs.language }}-${{ hashFiles('**/package-lock.json', '**/poetry.lock', '**/pom.xml', '**/build.gradle') }}
          restore-keys: |
            build-${{ runner.os }}-${{ inputs.language }}-
            build-${{ runner.os }}-

      - name: Install dependencies
        run: |
          case "${{ inputs.language }}" in
            node)
              npm ci --prefer-offline --no-audit
              ;;
            python)
              pip install --upgrade pip
              pip install -r requirements.txt --cache-dir ~/.cache/pip
              ;;
            java)
              ./mvnw dependency:go-offline || ./gradlew dependencies
              ;;
            go)
              go mod download
              ;;
          esac

      - name: Build application
        run: ${{ inputs.build-command }}
        env:
          NODE_ENV: production
          CI: true

      - name: Upload build artifacts
        id: upload
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            **/dist
            **/build
            **/target/*.jar
            **/*.whl
          retention-days: 30

  # Job 3: Test (runs in parallel with build)
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      coverage: ${{ steps.coverage.outputs.percentage }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Setup language environment
        uses: ./.github/actions/setup-environment
        with:
          language: ${{ inputs.language }}
          version: ${{ inputs.language-version }}

      - name: Restore dependency cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: |
            ~/.npm
            ~/.cache/pip
            ~/.m2/repository
            **/node_modules
          key: deps-${{ runner.os }}-${{ inputs.language }}-${{ hashFiles('**/package-lock.json', '**/requirements.txt', '**/pom.xml') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ inputs.language }}-

      - name: Install dependencies
        run: |
          case "${{ inputs.language }}" in
            node) npm ci --prefer-offline ;;
            python) pip install -r requirements.txt ;;
            java) ./mvnw dependency:resolve || ./gradlew dependencies ;;
            go) go mod download ;;
          esac

      - name: Run tests
        run: ${{ inputs.test-command }}
        env:
          CI: true

      - name: Generate coverage report
        id: coverage
        if: always()
        run: |
          if [ -f coverage/coverage-summary.json ]; then
            COVERAGE=$(jq '.total.lines.pct' coverage/coverage-summary.json)
            echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
          elif [ -f coverage.xml ]; then
            COVERAGE=$(python -c "import xml.etree.ElementTree as ET; print(round(float(ET.parse('coverage.xml').getroot().attrib['line-rate']) * 100, 2))")
            echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
          else
            echo "percentage=0" >> $GITHUB_OUTPUT
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: test-results
          path: |
            **/coverage/**
            **/test-results/**
            **/.coverage
            **/junit.xml
          retention-days: 14

      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const coverage = '${{ steps.coverage.outputs.percentage }}';
            const comment = `## Test Coverage Report\n\nðŸ“Š Coverage: **${coverage}%**\n\n${coverage >= 80 ? 'âœ… Meets coverage threshold' : 'âš ï¸ Below 80% coverage threshold'}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  # Job 4: Security Scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    if: inputs.enable-security-scan
    needs: [build]
    timeout-minutes: 15
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # v0.16.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@1b1aada464948af03b950897e5eb522f92603cc2 # v3.24.9
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Dependency review
        uses: actions/dependency-review-action@733dd5d4a5203f238c33806593ec0f5fc5343d8c # v4.1.3
        if: github.event_name == 'pull_request'

  # Job 5: Docker Build & Push
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: inputs.enable-docker
    needs: [test, security]
    timeout-minutes: 20
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3.2.0

      - name: Log in to Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ inputs.docker-registry }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

      - name: Generate SBOM
        uses: anchore/sbom-action@ab5d7b5f48981941c4c5d6bf33aeb98fe3bae38c # v0.15.10
        with:
          image: ${{ inputs.docker-registry }}/${{ github.repository }}@${{ steps.build.outputs.digest }}

  # Job 6: Notify
  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    if: always() && secrets.slack-webhook != ''
    needs: [lint, build, test, security, docker]
    steps:
      - name: Determine status
        id: status
        run: |
          if [[ "${{ needs.test.result }}" == "failure" || "${{ needs.security.result }}" == "failure" ]]; then
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "emoji=ðŸ”´" >> $GITHUB_OUTPUT
          elif [[ "${{ needs.test.result }}" == "success" && "${{ needs.security.result }}" == "success" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "emoji=ðŸŸ¢" >> $GITHUB_OUTPUT
          else
            echo "status=cancelled" >> $GITHUB_OUTPUT
            echo "emoji=âšª" >> $GITHUB_OUTPUT
          fi

      - name: Send Slack notification
        uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001 # v1.25.0
        with:
          webhook: ${{ secrets.slack-webhook }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "${{ steps.status.outputs.emoji }} CI Pipeline ${{ steps.status.outputs.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Status:* ${{ steps.status.outputs.status }}\n*Coverage:* ${{ needs.test.outputs.coverage }}%"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Run"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
