AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS WAF with OWASP Core Rule Set and DDoS Protection'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development

Resources:
  # WAF Web ACL
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${Environment}-waf-acl'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Rules:
        # AWS Managed Rule: Core Rule Set (OWASP Top 10)
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: []
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric

        # AWS Managed Rule: Known Bad Inputs
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSetMetric

        # AWS Managed Rule: SQL Injection
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesSQLiRuleSetMetric

        # Rate Limiting: 1000 requests per 5 minutes per IP
        - Name: RateLimitRule
          Priority: 4
          Action:
            Block:
              CustomResponse:
                ResponseCode: 429
                CustomResponseBodyKey: RateLimitResponse
          Statement:
            RateBasedStatement:
              Limit: 1000
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRuleMetric

        # Geo-blocking (block high-risk countries)
        - Name: GeoBlockingRule
          Priority: 5
          Action:
            Block: {}
          Statement:
            GeoMatchStatement:
              CountryCodes:
                - KP  # North Korea
                - IR  # Iran
                - SY  # Syria
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: GeoBlockingRuleMetric

        # IP Reputation List (AWS managed)
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 6
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAmazonIpReputationListMetric

        # Bot Control (detect and block bad bots)
        - Name: AWSManagedRulesBotControlRuleSet
          Priority: 7
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesBotControlRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesBotControlRuleSetMetric

      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${Environment}-waf-acl-metric'
      CustomResponseBodies:
        RateLimitResponse:
          ContentType: APPLICATION_JSON
          Content: '{"error": "Rate limit exceeded. Please try again later."}'

  # CloudWatch Log Group for WAF logs
  WAFLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/waf/${Environment}-acl'
      RetentionInDays: 30

  # WAF Logging Configuration
  WAFLoggingConfiguration:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt WebACL.Arn
      LogDestinationConfigs:
        - !GetAtt WAFLogGroup.Arn

  # AWS Shield Advanced (DDoS Protection)
  # Note: Shield Advanced is $3,000/month + data transfer costs
  # This is a reference - actual activation requires AWS support ticket

  # CloudWatch Alarms for WAF
  WAFBlockedRequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-waf-blocked-requests-high'
      AlarmDescription: 'Alert when WAF blocks unusually high number of requests'
      MetricName: BlockedRequests
      Namespace: AWS/WAFV2
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Rule
          Value: ALL
        - Name: WebACL
          Value: !Ref WebACL

  WAFRateLimitAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-waf-rate-limit-triggered'
      AlarmDescription: 'Alert when rate limiting is frequently triggered'
      MetricName: BlockedRequests
      Namespace: AWS/WAFV2
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 500
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Rule
          Value: RateLimitRule
        - Name: WebACL
          Value: !Ref WebACL

Outputs:
  WebACLId:
    Description: 'WAF Web ACL ID'
    Value: !GetAtt WebACL.Id
    Export:
      Name: !Sub '${Environment}-waf-acl-id'

  WebACLArn:
    Description: 'WAF Web ACL ARN (for ALB association)'
    Value: !GetAtt WebACL.Arn
    Export:
      Name: !Sub '${Environment}-waf-acl-arn'

# To associate WAF with ALB, add to your ALB stack:
# WebACLAssociation:
#   Type: AWS::WAFv2::WebACLAssociation
#   Properties:
#     ResourceArn: !Ref ApplicationLoadBalancerArn
#     WebACLArn: !ImportValue production-waf-acl-arn
